export default AFRAME.registerPrimitive('a-gui-slider', {
  defaultComponents: {
    'gui-interactable': {},
    'gui-item': { type: 'slider' },
    'gui-slider': {},
  },
  mappings: {
    'active-color': 'gui-slider.activeColor',
    'background-color': 'gui-slider.backgroundColor',
    'border-color': 'gui-slider.borderColor',
    'handle-color': 'gui-slider.handleColor',
    'handle-inner-depth': 'gui-slider.handleInnerDepth',
    'handle-inner-radius': 'gui-slider.handleInnerRadius',
    'handle-outer-depth': 'gui-slider.handleOuterDepth',
    'handle-outer-radius': 'gui-slider.handleOuterRadius',
    height: 'gui-item.height',
    'hover-color': 'gui-slider.hoverColor',
    'key-code': 'gui-interactable.keyCode',
    'left-right-padding': 'gui-slider.leftRightPadding',
    margin: 'gui-item.margin',
    onclick: 'gui-interactable.clickAction',
    onhover: 'gui-interactable.hoverAction',
    percent: 'gui-slider.percent',
    'slider-bar-depth': 'gui-slider.sliderBarDepth',
    'slider-bar-height': 'gui-slider.sliderBarHeight',
    'top-bottom-padding': 'gui-slider.topBottomPadding',
    width: 'gui-item.width',
  },
});
