export default AFRAME.registerPrimitive('a-gui-vertical-slider', {
  defaultComponents: {
    'gui-interactable': {},
    'gui-item': { type: 'slider' },
    'gui-vertical-slider': {},
  },
  mappings: {
    'active-color': 'gui-vertical-slider.activeColor',
    'background-color': 'gui-vertical-slider.backgroundColor',
    'border-color': 'gui-vertical-slider.borderColor',
    'handle-color': 'gui-vertical-slider.handleColor',
    'handle-inner-depth': 'gui-vertical-slider.handleInnerDepth',
    'handle-inner-radius': 'gui-vertical-slider.handleInnerRadius',
    'handle-outer-depth': 'gui-vertical-slider.handleOuterDepth',
    'handle-outer-radius': 'gui-vertical-slider.handleOuterRadius',
    height: 'gui-item.height',
    'hover-color': 'gui-vertical-slider.hoverColor',
    'hover-font-size': 'gui-vertical-slider.hoverFontSize',
    'hover-height': 'gui-vertical-slider.hoverHeight',
    'hover-margin': 'gui-vertical-slider.hoverMargin',
    'hover-percent': 'gui-vertical-slider.hoverPercent',
    'hover-width': 'gui-vertical-slider.hoverWidth',
    'key-code': 'gui-interactable.keyCode',
    'left-right-padding': 'gui-vertical-slider.leftRightPadding',
    margin: 'gui-item.margin',
    onclick: 'gui-interactable.clickAction',
    onhover: 'gui-interactable.hoverAction',
    opacity: 'gui-vertical-slider.opacity',
    'output-font-size': 'gui-vertical-slider.outputFontSize',
    'output-function': 'gui-vertical-slider.outputFunction',
    'output-height': 'gui-vertical-slider.outputHeight',
    'output-margin': 'gui-vertical-slider.outputMargin',
    'output-text-depth': 'gui-vertical-slider.outputTextDepth',
    'output-width': 'gui-vertical-slider.outputWidth',
    percent: 'gui-vertical-slider.percent',
    'slider-bar-depth': 'gui-vertical-slider.sliderBarDepth',
    'slider-bar-width': 'gui-vertical-slider.sliderBarWidth',
    'top-bottom-padding': 'gui-vertical-slider.topBottomPadding',
    width: 'gui-item.width',
  },
});
