import type { GetStaticProps, NextPage } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import ToggleThemeButton from '@react-components/ToggleThemeButton';
import styles from '../styles/Home.module.css';
import React from 'react';
import MainPage from '@react-components/MainPage';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meta Composer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ToggleThemeButton />
      </main>
      <MainPage />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale || 'ko', ['common'])),
  },
});

export default Home;
