import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Button from '../react-components/common/Button';
import ToggleThemeButton from '../react-components/ToggleThemeButton';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button className="btn w-64 rounded-full">Daisy UI Button</button>
        <ToggleThemeButton />
      </main>
    </div>
  );
};

export default Home;
